### ISSUE TITLE
Test suite fails

### ISSUE THREAD

**Issue by psybers** [anthonyu/Sizzle#3]
One of the test suites fails.  This makes it impossible to build the package ('ant package') because junit is set to haltonfailure.

```
[junit] Testsuite: sizzle.compiler.TestCodeGeneratingVisitor
[junit] Tests run: 14, Failures: 0, Errors: 14, Time elapsed: 3.429 sec
[junit] ------------- Standard Error -----------------
[junit] error(10):  internal error: no such group file SizzleJavaHadoop.stg 
[junit] 
[junit] 12/05/20 20:40:27 INFO security.Groups: Group mapping impl=org.apache.hadoop.security.ShellBasedUnixGroupsMapping; cacheTimeout=300000
[junit] ------------- ---------------- ---------------
[junit] 
[junit] Testcase: testCodeGeneratingVisitorSimple took 1.165 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorSimple(TestCodeGeneratingVisitor.java:111)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorSimpleCompound took 0.177 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorSimpleCompound(TestCodeGeneratingVisitor.java:151)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorQuickExample took 0.145 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorQuickExample(TestCodeGeneratingVisitor.java:189)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorRealWordCount took 0.257 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorRealWordCount(TestCodeGeneratingVisitor.java:232)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorWordStats took 0.251 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorWordStats(TestCodeGeneratingVisitor.java:296)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorFilteredMeanValue took 0.106 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorFilteredMeanValue(TestCodeGeneratingVisitor.java:345)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorStringConversion took 0.114 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorStringConversion(TestCodeGeneratingVisitor.java:388)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorValueQuartiles took 0.104 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorValueQuartiles(TestCodeGeneratingVisitor.java:432)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorMaps took 0.107 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorMaps(TestCodeGeneratingVisitor.java:515)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorUppercaseMap took 0.103 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorUppercaseMap(TestCodeGeneratingVisitor.java:555)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorTimeParser took 0.115 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorTimeParser(TestCodeGeneratingVisitor.java:591)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorTopReferers took 0.117 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorTopReferers(TestCodeGeneratingVisitor.java:627)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorRegex took 0.133 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorRegex(TestCodeGeneratingVisitor.java:667)
[junit] 
[junit] Testcase: testCodeGeneratingVisitorHello took 0.098 sec
[junit]     Caused an ERROR
[junit] null
[junit] java.lang.NullPointerException
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:185)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:152)
[junit]     at sizzle.parser.syntaxtree.Program.accept(Program.java:22)
[junit]     at sizzle.compiler.CodeGeneratingVisitor.visit(CodeGeneratingVisitor.java:180)
[junit]     at sizzle.compiler.TestCodeGeneratingVisitor.testCodeGeneratingVisitorHello(TestCodeGeneratingVisitor.java:76)
[junit] 
[junit] Test sizzle.compiler.TestCodeGeneratingVisitor FAILED
```

**Comment by psybers** [comment]
I think this is related.  I also can't compile any of the example programs because it has a NPE trying to load the .stg files.

$ java -jar ../dist/sizzle-compiler.jar -h ~/hadoop-0.21.0/ -i best_referers.szl 
Exception in thread "main" java.lang.NullPointerException
    at sizzle.compiler.SizzleCompiler.main(SizzleCompiler.java:153)

**Comment by anthonyu** [comment]
This has been fixed thanks to a patch by psybers.
